
USE isler_kitabevi;


SELECT YEAR(date) as yil, COUNT(*) as kayit FROM sales GROUP BY YEAR(date);


INSERT INTO sales (branch_id, date, category, quantity, revenue)
SELECT b.id, DATE(CONCAT('2023-', LPAD(m.m, 2, '0'), '-15')), c.cat,
    FLOOR(80 + RAND() * 150), ROUND((80 + RAND() * 150) * (20 + RAND() * 12), 2)
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
CROSS JOIN (SELECT 'Books' cat UNION SELECT 'Stationery' UNION SELECT 'Kids' UNION SELECT 'Gifts') c
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM sales WHERE YEAR(date) = 2023 LIMIT 1);


INSERT INTO expenses (branch_id, date, expense_type, amount)
SELECT b.id, DATE(CONCAT('2023-', LPAD(m.m, 2, '0'), '-01')), 'Rent',
    CASE b.id WHEN 1 THEN 22000 WHEN 2 THEN 25000 WHEN 3 THEN 20000 ELSE 15000 END
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM expenses WHERE YEAR(date) = 2023 LIMIT 1);

INSERT INTO expenses (branch_id, date, expense_type, amount)
SELECT b.id, DATE(CONCAT('2023-', LPAD(m.m, 2, '0'), '-01')), 'Salary',
    CASE b.id WHEN 1 THEN 40000 WHEN 2 THEN 45000 WHEN 3 THEN 38000 ELSE 30000 END
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM expenses WHERE YEAR(date) = 2023 AND expense_type = 'Salary' LIMIT 1);


INSERT INTO sales (branch_id, date, category, quantity, revenue)
SELECT b.id, DATE(CONCAT('2024-', LPAD(m.m, 2, '0'), '-15')), c.cat,
    FLOOR(100 + RAND() * 180), ROUND((100 + RAND() * 180) * (24 + RAND() * 14), 2)
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
CROSS JOIN (SELECT 'Books' cat UNION SELECT 'Stationery' UNION SELECT 'Kids' UNION SELECT 'Gifts') c
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM sales WHERE YEAR(date) = 2024 LIMIT 1);


INSERT INTO expenses (branch_id, date, expense_type, amount)
SELECT b.id, DATE(CONCAT('2024-', LPAD(m.m, 2, '0'), '-01')), 'Rent',
    CASE b.id WHEN 1 THEN 28000 WHEN 2 THEN 32000 WHEN 3 THEN 25000 ELSE 18000 END
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM expenses WHERE YEAR(date) = 2024 LIMIT 1);

INSERT INTO expenses (branch_id, date, expense_type, amount)
SELECT b.id, DATE(CONCAT('2024-', LPAD(m.m, 2, '0'), '-01')), 'Salary',
    CASE b.id WHEN 1 THEN 50000 WHEN 2 THEN 55000 WHEN 3 THEN 45000 ELSE 35000 END
FROM branches b
CROSS JOIN (SELECT 1 m UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 
            UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12) m
WHERE b.status = 'Active'
AND NOT EXISTS (SELECT 1 FROM expenses WHERE YEAR(date) = 2024 AND expense_type = 'Salary' LIMIT 1);


SELECT YEAR(date) as Yil, COUNT(*) as Satis FROM sales GROUP BY YEAR(date);
SELECT YEAR(date) as Yil, COUNT(*) as Gider FROM expenses GROUP BY YEAR(date);
