
USE isler_kitabevi;


DELETE FROM sales WHERE YEAR(date) = 2024;
DELETE FROM expenses WHERE YEAR(date) = 2024;


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 1, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(8000 + RAND() * 4000),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(80 + RAND() * 50)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 1, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(50000 + RAND() * 20000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 2, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(7500 + RAND() * 3500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(70 + RAND() * 40)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 2, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(45000 + RAND() * 15000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 3, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(7000 + RAND() * 3000),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(65 + RAND() * 35)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 3, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(40000 + RAND() * 15000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 4, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(6500 + RAND() * 2500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(60 + RAND() * 30)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 4, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(35000 + RAND() * 12000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 5, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(6000 + RAND() * 2500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(55 + RAND() * 30)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 5, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(32000 + RAND() * 10000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 6, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(2000 + RAND() * 1500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(20 + RAND() * 15)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 6, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(80000 + RAND() * 20000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 7, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(1800 + RAND() * 1200),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(18 + RAND() * 12)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 7, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(75000 + RAND() * 20000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 8, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(4000 + RAND() * 2000),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(40 + RAND() * 20)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 8, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(85000 + RAND() * 25000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 9, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(3500 + RAND() * 1500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(35 + RAND() * 15)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 9, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(70000 + RAND() * 20000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 10, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(3200 + RAND() * 1800),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(32 + RAND() * 18)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 10, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(68000 + RAND() * 18000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 11, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(4500 + RAND() * 1500),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(45 + RAND() * 15)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 11, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(48000 + RAND() * 12000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


INSERT INTO sales (branch_id, date, amount, category, customer_count)
SELECT 12, DATE_ADD('2024-01-01', INTERVAL n DAY), 
       FLOOR(4200 + RAND() * 1600),
       ELT(FLOOR(1 + RAND() * 3), 'Kitap', 'Kırtasiye', 'Dergi'),
       FLOOR(42 + RAND() * 16)
FROM (SELECT a.N + b.N * 10 + c.N * 100 as n FROM 
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3) c) numbers
WHERE DATE_ADD('2024-01-01', INTERVAL n DAY) <= '2024-12-21';

INSERT INTO expenses (branch_id, date, amount, category, description)
SELECT 12, DATE_ADD('2024-01-01', INTERVAL n*30 DAY),
       FLOOR(45000 + RAND() * 12000),
       ELT(FLOOR(1 + RAND() * 4), 'Kira', 'Personel', 'Fatura', 'Malzeme'),
       'Aylık gider'
FROM (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11) months
WHERE DATE_ADD('2024-01-01', INTERVAL n*30 DAY) <= '2024-12-21';


SELECT b.name, 
       COALESCE(SUM(s.amount), 0) as toplam_gelir,
       COALESCE((SELECT SUM(amount) FROM expenses WHERE branch_id = b.id AND YEAR(date) = 2024), 0) as toplam_gider,
       COALESCE(SUM(s.amount), 0) - COALESCE((SELECT SUM(amount) FROM expenses WHERE branch_id = b.id AND YEAR(date) = 2024), 0) as kar_zarar
FROM branches b
LEFT JOIN sales s ON b.id = s.branch_id AND YEAR(s.date) = 2024
GROUP BY b.id, b.name
ORDER BY kar_zarar DESC;
